/*============================================================================*
 *                                                                            *
 *	This file is part of the Zoto Software Suite.  							  *
 *																			  *
 *	Copyright (C) 2004, 2005 Zoto, Inc.  123 South Hudson, OKC, OK  73102	  *
 *																			  *
 *  This program is free software; you can redistribute it and/or modify      *
 *  it under the terms of the GNU General Public License as published by      *
 *  the Free Software Foundation; either version 2 of the License, or         *
 *  (at your option) any later version.                                       *
 *                                                                            *
 *  This program is distributed in the hope that it will be useful,           *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             *
 *  GNU General Public License for more details.                              *
 *                                                                            *
 *  You should have received a copy of the GNU General Public License         *
 *  along with this program; if not, write to the Free Software               *
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA *
 *                                                                            *
 *============================================================================*
 *                                  CHANGELOG                                 *
 *   Date       Description                                    Author         *
 * -----------  ---------------------------------------------  -------------- *
 *                                                                            *
 *============================================================================*/
#if !defined(__ZIMAGEREQUEST_H_INCLUDED__)
#define __ZIMAGEREQUEST_H_INCLUDED__

/* System Headers */
#include <qstring.h>

/* Local Headers */
#include "ZTypes.h"

/* Macros */

namespace ZOTO
{

/**
 *	@class		ZImageRequest
 *
 *	@brief		Pixmap load request
 *	@author		Josh Williams
 *	@version	0.1.0
 *	@date		01-Apr-2005
 *
 *	@remarks	Generated by the view when an image is added.
 */
class ZImageRequest
{
public:
	/*==================================*
	 *	   CONSTRUCTION/DESTRUCTION		*
	 *==================================*/
	ZImageRequest() {}
	ZImageRequest(ZULONG pKey, QString pURI, int pWidth, int pHeight)
		: mKey(pKey), mURI(pURI), mWidth(pWidth), mHeight(pHeight) {}
	ZImageRequest(const ZImageRequest& rhs)
		: mKey(rhs.GetKey()), mURI(rhs.GetURI()), mWidth(rhs.GetWidth()), mHeight(rhs.GetHeight()) {}

public:
	/*==================================*
	 *			  ATTRIBUTES			*
	 *==================================*/
	ZULONG				GetKey() const;
	const QString&		GetURI() const;
	int					GetWidth() const;
	int					GetHeight() const;

public:
	/*==================================*
	 *			  OPERATIONS			*
	 *==================================*/

protected:
	/*==================================*
	 *             CALLBACKS			*
	 *==================================*/

private:
	/*==================================*
	 *			  INTERNALS				*
	 *==================================*/

private:
	/*==================================*
	 *             VARIABLES            *
	 *==================================*/
	ZULONG				mKey;		/**< Unique ID for this image */
	QString				mURI;		/**< File to be loaded */
	int					mWidth;		/**< Width for the thumbnail */
	int					mHeight;	/**< Height for the thumbnail */
};



/********************************************************************
 *																	*
 *							I N L I N E S							*
 *																	*
 ********************************************************************/
/**
 *	Gets the request ID associated with this item.
 */
inline
ZULONG ZImageRequest::GetKey() const
{
	return mKey;
}

/**
 *	Gets the file path that is to be loaded.
 */
inline
const QString& ZImageRequest::GetURI() const
{
	return mURI;
}

/**
 *	Gets the file path that is to be loaded.
 */
inline
int ZImageRequest::GetWidth() const
{
	return mWidth;
}

/**
 *	Gets the file path that is to be loaded.
 */
inline
int ZImageRequest::GetHeight() const
{
	return mHeight;
}

} // End Namespace

#endif // __ZIMAGEREQUEST_H_INCLUDED__

/* vi: set ts=4: */
