; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

;==================================
; Global Defines
;==================================
#define VERSMAJ		ReadIni('..\zulu-gui\zotorc','Zulu','VersMaj','0')
#define VERSMIN		ReadIni('..\zulu-gui\zotorc','Zulu','VersMin','0')
#define VERSBUILD	ReadIni('..\zulu-gui\zotorc','Zulu','VersBuild','0')
#define ZSPHOST		ReadIni('..\zulu-gui\zotorc','Zulu','ZSP/ZspHost','zoto.com')
#define ZSPPORT		Int(ReadIni('..\zulu-gui\zotorc','Zulu','ZSP/ZspPort','35001'))
#define ZAPIHOST	ReadIni('..\zulu-gui\zotorc','Zulu','ZAPI/ZapiHost','zoto.com')
#define ZAPIPORT	Int(ReadIni('..\zulu-gui\zotorc','Zulu','ZAPI/ZapiPort','80'))
#define ZAPIPATH	ReadIni('..\zulu-gui\zotorc','Zulu','ZAPI/ZapiPath','/RPC2/')

[Setup]
AppName=Zoto Uploader
AppVerName=Zoto Uploader {#VERSMAJ}.{#VERSMIN}.{#VERSBUILD}
AppPublisher=Zoto, Inc.
AppPublisherURL=http://www.zoto.com
AppSupportURL=http://www.zoto.com
AppUpdatesURL=http://www.zoto.com/general/downloads/
DefaultDirName={pf}\Zoto
DefaultGroupName=Zoto
OutputBaseFilename=Zoto Uploader {#VERSMAJ}.{#VERSMIN}.{#VERSBUILD}
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: ..\zulu-gui\Release\zulu.exe; DestDir: {app}; Flags: ignoreversion
Source: ..\zshell\Release\zshell.exe; DestDir: {app}; Flags: ignoreversion
Source: zoto.url; DestDir: {app}
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; .jpg
Root: HKCR; Subkey: SystemFileAssociations\.jpg\shell; Flags: uninsdeletekeyifempty
Root: HKCR; Subkey: SystemFileAssociations\.jpg\shell\edit.Zoto; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.jpg\shell\edit.Zoto; ValueType: string; ValueName: ; ValueData: Upload to Zoto ...
Root: HKCR; Subkey: SystemFileAssociations\.jpg\shell\edit.Zoto\command; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.jpg\shell\edit.Zoto\command; ValueType: string; ValueName: ; ValueData: """{app}\zshell.exe"" ""%1"""
; .jpeg
Root: HKCR; Subkey: SystemFileAssociations\.jpeg\shell; Flags: uninsdeletekeyifempty
Root: HKCR; Subkey: SystemFileAssociations\.jpeg\shell\edit.Zoto; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.jpeg\shell\edit.Zoto; ValueType: string; ValueName: ; ValueData: Upload to Zoto ...
Root: HKCR; Subkey: SystemFileAssociations\.jpeg\shell\edit.Zoto\command; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.jpeg\shell\edit.Zoto\command; ValueType: string; ValueName: ; ValueData: """{app}\zshell.exe"" ""%1"""
; .jpe
Root: HKCR; Subkey: SystemFileAssociations\.jpe\shell; Flags: uninsdeletekeyifempty
Root: HKCR; Subkey: SystemFileAssociations\.jpe\shell\edit.Zoto; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.jpe\shell\edit.Zoto; ValueType: string; ValueName: ; ValueData: Upload to Zoto ...
Root: HKCR; Subkey: SystemFileAssociations\.jpe\shell\edit.Zoto\command; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.jpe\shell\edit.Zoto\command; ValueType: string; ValueName: ; ValueData: """{app}\zshell.exe"" ""%1"""
; .gif
Root: HKCR; Subkey: SystemFileAssociations\.gif\shell; Flags: uninsdeletekeyifempty
Root: HKCR; Subkey: SystemFileAssociations\.gif\shell\edit.Zoto; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.gif\shell\edit.Zoto; ValueType: string; ValueName: ; ValueData: Upload to Zoto ...
Root: HKCR; Subkey: SystemFileAssociations\.gif\shell\edit.Zoto\command; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.gif\shell\edit.Zoto\command; ValueType: string; ValueName: ; ValueData: """{app}\zshell.exe"" ""%1"""
; .png
Root: HKCR; Subkey: SystemFileAssociations\.png\shell; Flags: uninsdeletekeyifempty
Root: HKCR; Subkey: SystemFileAssociations\.png\shell\edit.Zoto; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.png\shell\edit.Zoto; ValueType: string; ValueName: ; ValueData: Upload to Zoto ...
Root: HKCR; Subkey: SystemFileAssociations\.png\shell\edit.Zoto\command; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.png\shell\edit.Zoto\command; ValueType: string; ValueName: ; ValueData: """{app}\zshell.exe"" ""%1"""
; .bmp
Root: HKCR; Subkey: SystemFileAssociations\.bmp\shell; Flags: uninsdeletekeyifempty
Root: HKCR; Subkey: SystemFileAssociations\.bmp\shell\edit.Zoto; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.bmp\shell\edit.Zoto; ValueType: string; ValueName: ; ValueData: Upload to Zoto ...
Root: HKCR; Subkey: SystemFileAssociations\.bmp\shell\edit.Zoto\command; Flags: uninsdeletekey
Root: HKCR; Subkey: SystemFileAssociations\.bmp\shell\edit.Zoto\command; ValueType: string; ValueName: ; ValueData: """{app}\zshell.exe"" ""%1"""

; Zulu main hive
Root: HKCU; Subkey: Software\Zoto; Flags: Uninsdeletekey
Root: HKCU; Subkey: Software\Zoto\Zulu
Root: HKCU; Subkey: Software\Zoto\Zulu; ValueType: dword; ValueName: VersMaj; ValueData: {#VERSMAJ}
Root: HKCU; Subkey: Software\Zoto\Zulu; ValueType: dword; ValueName: VersMin; ValueData: {#VERSMIN}
Root: HKCU; Subkey: Software\Zoto\Zulu; ValueType: dword; ValueName: VersBuild; ValueData: {#VERSBUILD}
Root: HKCU; Subkey: Software\Zoto\Zulu\ZSP; ValueType: string; ValueName: ZspHost; ValueData: {#ZSPHOST}
Root: HKCU; Subkey: Software\Zoto\Zulu\ZSP; ValueType: dword; ValueName: ZspPort; ValueData: {#ZSPPORT}
Root: HKCU; Subkey: Software\Zoto\Zulu\ZAPI; ValueType: string; ValueName: ZapiHost; ValueData: {#ZAPIHOST}
Root: HKCU; Subkey: Software\Zoto\Zulu\ZAPI; ValueType: dword; ValueName: ZapiPort; ValueData: {#ZAPIPORT}
Root: HKCU; Subkey: Software\Zoto\Zulu\ZAPI; ValueType: string; ValueName: ZapiPath; ValueData: {#ZAPIPATH}



[Icons]
Name: {group}\Zoto Uploader; Filename: {app}\zulu.exe
Name: {group}\Uninstall Zoto Uploader; Filename: {uninstallexe}
Name: {group}\Zoto Uploader Help; Filename: {app}\zoto.url
Name: {userdesktop}\Zoto Uploader; Filename: {app}\zulu.exe; Tasks: desktopicon

[Run]
Filename: {app}\zulu.exe; Description: {cm:LaunchProgram,Zoto Uploader}; Flags: nowait postinstall skipifsilent
