"""
UserError.py -- User Error Class

Ken Kinder
2004-05-07
"""

from AZTKError import AZTKError

class UserError(AZTKError):
	description = "User Error"
	
	ADMIN_SIMULATED_ERROR           = 1100
	BLOG_DISCOVERY_ERROR            = 2100
	BLOG_DISCOVERY_NO_SUPPORT       = 2200
	BLOG_INVALID_USER               = 2300
	BLOG_INVALID_URL                = 2400
	IMAGES_ALREADY_EXISTS           = 3100
	IMAGES_NO_ORIGINAL              = 3500
	IMAGES_NOT_VIEWABLE             = 3600
	SEARCH_NO_TERMS                 = 4100
	USERS_USERNAME_TAKEN            = 5100
	USERS_EMAIL_TAKEN               = 5105
	USERS_USERNAME_LENGTH           = 5110
	USERS_INVALID_USERNAME          = 5120
	USERS_INVALID_ZIP               = 5200
	USERS_ACTIVATION_EXPIRED        = 5300
	USERS_NO_USER                   = 5400
	USERS_INVALID_EMAIL             = 5450
	USERS_RECOVERY_KEY_EXPIRED      = 5500
	USERS_ACTIVATION_EXPIRED        = 5600
	USERS_BAD_PROMOTION_CODE        = 5700
	VALIDATION_UNKNOWN_FILETYPE     = 6100
	VALIDATION_UNSUPPORTED_FILETYPE = 6200
	VALIDATION_BAD_DATE             = 6300
	VALIDATION_BAD_EMAIL            = 6400
	ZSP_UNSUPPORTED_FILETYPE        = 7100
	IMAGE_NOT_IN_LIGHTBOX           = 8100
	ACCT_OVER_DISK_QUOTA            = 9100
	ACCT_NO_PERMS                   = 9200
	ACCT_LOGIN_SUSPENDED            = 9500
	ACCT_BROWSE_SUSPENDED           = 9550
	GALLERIES_INVALID_PASSWORD      = 10000
	GALLERIES_MAX_GALLERIES		= 11000

